{% set name = "larixite" %}
{% set version = "2026.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/larixite-{{ version }}.tar.gz
  sha256: ba1dd68b76f181f5a0a547fda9eb4dc06fe61e40c4bbf25f513ff30ede0b68e8
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - xraydb
    - sqlalchemy >=2
    - pymatgen >=2025.6.14
    - mp-api >=0.45.8
    - emmet-core >=0.84.9

test:
  imports:
    - larixite
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: convert CIF data to inputs for XAS calculations Feff, FDMNES, etc
  license: MIT
  license_file: LICENSE
  home: https://xraypy.github.io/larixite/
  dev_url: https://github.com/xraypy/larixite

extra:
  recipe-maintainers:
    - mrakitin
    - maurov
