{% set name = "larixite" %}
{% set version = "2025.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/larixite-{{ version }}.tar.gz
  sha256: 69c159ed24568a65dc3968766721a36cdbc261ea124e367d67f1fb785b4cabf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - xraydb
    - sqlalchemy >=2
    - pymatgen
    - pyshortcuts

test:
  imports:
    - larixite
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: convert CIF data to inputs for XAS calculations Feff, FDMNES, etc
  license: MIT
  license_file: LICENSE
  home: https://xraypy.github.io/larixite/
  dev_url: https://github.com/xraypy/larixite

extra:
  recipe-maintainers:
    - mrakitin
